import type { AssessmentResult, Instrument } from "@core/types";
import type { PersonalityReport } from "@core/report";

export function downloadText(filename: string, text: string, mime = "text/plain") {
  const blob = new Blob([text], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadJSON(instrument: Instrument, result: AssessmentResult, report: PersonalityReport) {
  downloadText(
    `psyche-atlas-${report.reportId}.json`,
    JSON.stringify({ instrument: instrument.id, takenAt: result.takenAt, result, report }, null, 2),
    "application/json",
  );
}

export function reportToMarkdown(instrument: Instrument, report: PersonalityReport): string {
  const L: string[] = [];
  L.push(`# ${report.title}`);
  L.push(`_${report.subtitle}_ — ${instrument.name}, report #${report.reportId}`);
  L.push("");
  L.push(`> ${report.uniqueness.note}`);
  L.push("");
  L.push("## Overview");
  report.overview.forEach((p) => L.push(p + "\n"));

  if (report.type) {
    L.push(`## Your type: ${report.type.code} — ${report.type.title}`);
    L.push(report.type.summary + "\n");
    report.type.components.forEach((c) => L.push(`- **${c.label}:** ${c.value}${c.detail ? ` (${c.detail})` : ""}`));
    L.push("");
  }

  L.push("## Profile");
  report.traits.forEach((t) => L.push(`- **${t.name}** — ${t.level} (${Math.round(t.percentile)}th percentile)`));
  L.push("");

  L.push("## Trait by trait");
  report.traits.forEach((t) => {
    L.push(`### ${t.name} — ${t.level} (${Math.round(t.percentile)}th pct)`);
    L.push(t.narrative);
    L.push(`**Strengths:** ${t.strengths.join("; ")}`);
    L.push(`**Watch-outs:** ${t.watchouts.join("; ")}\n`);
  });

  if (report.dynamics.length) {
    L.push("## How your traits interact");
    report.dynamics.forEach((d) => L.push(`- ${d}`));
    L.push("");
  }

  report.sections.forEach((sec) => {
    L.push(`## ${sec.heading}`);
    sec.paragraphs.forEach((p) => L.push(p + "\n"));
    (sec.bullets ?? []).forEach((b) => L.push(`- ${b}`));
    L.push("");
  });

  if (report.signatureResponses.length) {
    L.push("## What makes this uniquely yours");
    report.signatureResponses.forEach((sgn) => L.push(`- ${sgn}`));
    L.push("");
  }

  L.push("## Scientific basis");
  L.push(instrument.itemProvenance);
  instrument.citations.forEach((c) => L.push(`- ${c.ref}`));
  L.push("");
  L.push(`_Generated by Psyche Atlas · engine: ${report.engine} · ${new Date(report.generatedAt).toLocaleString()}_`);
  return L.join("\n");
}

export function downloadMarkdown(instrument: Instrument, report: PersonalityReport) {
  downloadText(`psyche-atlas-${report.reportId}.md`, reportToMarkdown(instrument, report), "text/markdown");
}
