import type { AssessmentResult, Instrument } from "@core/types";
import type { PersonalityReport } from "@core/report";
import type { IntegratedProfile } from "@core/synthesis";

export function downloadText(filename: string, text: string, mime = "text/plain") {
  const blob = new Blob([text], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadJSON(instrument: Instrument, result: AssessmentResult, report: PersonalityReport) {
  downloadText(
    `psyche-atlas-${report.reportId}.json`,
    JSON.stringify({ instrument: instrument.id, takenAt: result.takenAt, result, report }, null, 2),
    "application/json",
  );
}

export function reportToMarkdown(instrument: Instrument, report: PersonalityReport): string {
  const L: string[] = [];
  L.push(`# ${report.title}`);
  L.push(`_${report.subtitle}_ — ${instrument.name}, report #${report.reportId}`);
  L.push("");
  L.push(`> ${report.uniqueness.note}`);
  L.push("");
  L.push("## Overview");
  report.overview.forEach((p) => L.push(p + "\n"));

  if (report.type) {
    L.push(`## Your type: ${report.type.code} — ${report.type.title}`);
    L.push(report.type.summary + "\n");
    report.type.components.forEach((c) => L.push(`- **${c.label}:** ${c.value}${c.detail ? ` (${c.detail})` : ""}`));
    L.push("");
  }

  L.push("## Profile");
  report.traits.forEach((t) => L.push(`- **${t.name}** — ${t.level} (${Math.round(t.percentile)}th percentile)`));
  L.push("");

  L.push("## Trait by trait");
  report.traits.forEach((t) => {
    L.push(`### ${t.name} — ${t.level} (${Math.round(t.percentile)}th pct)`);
    L.push(t.narrative);
    L.push(`**Strengths:** ${t.strengths.join("; ")}`);
    L.push(`**Watch-outs:** ${t.watchouts.join("; ")}\n`);
  });

  if (report.dynamics.length) {
    L.push("## How your traits interact");
    report.dynamics.forEach((d) => L.push(`- ${d}`));
    L.push("");
  }

  report.sections.forEach((sec) => {
    L.push(`## ${sec.heading}`);
    sec.paragraphs.forEach((p) => L.push(p + "\n"));
    (sec.bullets ?? []).forEach((b) => L.push(`- ${b}`));
    L.push("");
  });

  if (report.signatureResponses.length) {
    L.push("## What makes this uniquely yours");
    report.signatureResponses.forEach((sgn) => L.push(`- ${sgn}`));
    L.push("");
  }

  L.push("## Scientific basis");
  L.push(instrument.itemProvenance);
  instrument.citations.forEach((c) => L.push(`- ${c.ref}`));
  L.push("");
  L.push(`_Generated by Psyche Atlas · engine: ${report.engine} · ${new Date(report.generatedAt).toLocaleString()}_`);
  return L.join("\n");
}

export function downloadMarkdown(instrument: Instrument, report: PersonalityReport) {
  downloadText(`psyche-atlas-${report.reportId}.md`, reportToMarkdown(instrument, report), "text/markdown");
}

/** Localized section labels for the integrated-portrait export. */
export interface IntegratedLabels {
  title: string; threads: string; manual: string; crosscheck: string; readstyle: string;
  strengths: string; growth: string; tensions: string; from: string; generated: string;
  comm?: string;
}

export function integratedToMarkdown(ip: IntegratedProfile, l: IntegratedLabels): string {
  const L: string[] = [];
  L.push(`# ${ip.headline}`);
  L.push(`_${ip.subhead}_ — ${l.title} · #${ip.reportId}`);
  L.push("");
  ip.overview.forEach((p) => L.push(p + "\n"));

  L.push(`_${l.from.replace("{n}", String(ip.instrumentsUsed.length))}: ${ip.instrumentsUsed.map((u) => u.name).join(", ")}_`);
  L.push("");

  if (ip.themes.length) {
    L.push(`## ${l.threads}`);
    ip.themes.forEach((t) => { L.push(`### ${t.name}`); L.push(t.narrative + "\n"); });
  }

  L.push(`## ${l.manual}`);
  ip.operatingManual.forEach((o) => L.push(`- **${o.label}:** ${o.text}`));
  L.push("");

  if (ip.convergence.readings.length) {
    L.push(`## ${l.crosscheck}`);
    ip.convergence.readings.forEach((r) => L.push(`- **${r.name}** (${r.band}) — ${r.insight}`));
    L.push("");
  }

  if (ip.communication && ip.communication.themes.length) {
    L.push(`## ${l.comm ?? "Communication portrait"}`);
    ip.communication.themes.forEach((th) => L.push(`- **${th.name}** (${th.score}/100, ${th.band})`));
    L.push("");
    L.push(ip.communication.insight + "\n");
  }

  if (ip.responseStyle.summary) {
    L.push(`## ${l.readstyle}`);
    L.push(ip.responseStyle.summary);
    ip.responseStyle.flags.forEach((f) => L.push(`- **${f.label}** — ${f.note}`));
    L.push("");
  }

  if (ip.strengths.length) { L.push(`## ${l.strengths}`); ip.strengths.forEach((s) => L.push(`- ${s}`)); L.push(""); }
  if (ip.growthEdges.length) { L.push(`## ${l.growth}`); ip.growthEdges.forEach((s) => L.push(`- ${s}`)); L.push(""); }
  if (ip.tensions.length) {
    L.push(`## ${l.tensions}`);
    ip.tensions.forEach((t) => L.push(`- **${t.title}** — ${t.detail}`));
    L.push("");
  }

  L.push(`_${l.generated} · ${new Date(ip.generatedAt).toLocaleString()}_`);
  return L.join("\n");
}

export function downloadIntegratedMarkdown(ip: IntegratedProfile, l: IntegratedLabels) {
  downloadText(`psyche-atlas-integrated-${ip.reportId}.md`, integratedToMarkdown(ip, l), "text/markdown");
}
