/**
 * Determinism & uniqueness primitives.
 *
 * The report engine must be reproducible from a seed (so a saved report can be
 * regenerated byte-for-byte) yet practically *never* repeat across users. We get
 * both by deriving a seed from the full response vector PLUS a high-entropy nonce
 * and timestamp: same seed -> identical text; any change -> different text.
 */

/** cyrb53 — a fast, well-distributed 53-bit string hash (public domain). */
export function cyrb53(str: string, seed = 0): number {
  let h1 = 0xdeadbeef ^ seed;
  let h2 = 0x41c6ce57 ^ seed;
  for (let i = 0; i < str.length; i++) {
    const ch = str.charCodeAt(i);
    h1 = Math.imul(h1 ^ ch, 2654435761);
    h2 = Math.imul(h2 ^ ch, 1597334677);
  }
  h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507);
  h1 ^= Math.imul(h2 ^ (h2 >>> 13), 3266489909);
  h2 = Math.imul(h2 ^ (h2 >>> 16), 2246822507);
  h2 ^= Math.imul(h1 ^ (h1 >>> 13), 3266489909);
  return 4294967296 * (2097151 & h2) + (h1 >>> 0);
}

/** Hash to a hex string for fingerprints. */
export function hashHex(str: string, seed = 0): string {
  return cyrb53(str, seed).toString(16).padStart(14, "0");
}

/** mulberry32 — compact, high-quality 32-bit seeded PRNG. */
export function mulberry32(a: number): () => number {
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Cryptographically-strong random hex nonce (browser & Node 18+). */
export function nonce(bytes = 16): string {
  const g: any = globalThis as any;
  if (g.crypto?.getRandomValues) {
    const arr = new Uint8Array(bytes);
    g.crypto.getRandomValues(arr);
    return Array.from(arr, (b) => b.toString(16).padStart(2, "0")).join("");
  }
  // Fallback (should not be hit in supported runtimes).
  let s = "";
  for (let i = 0; i < bytes * 2; i++) s += Math.floor(Math.random() * 16).toString(16);
  return s;
}

/** Derive a numeric seed from arbitrary string parts. */
export function seedFrom(...parts: (string | number)[]): number {
  return cyrb53(parts.join("␟"));
}

/**
 * A seeded random source with ergonomic helpers used throughout the composer.
 * Deterministic given its seed; advancing it never repeats the global PRNG state.
 */
export class Rng {
  private next: () => number;
  constructor(seed: number) {
    this.next = mulberry32(seed >>> 0);
  }
  /** Uniform float in [0, 1). */
  float(): number {
    return this.next();
  }
  /** Integer in [0, maxExclusive). */
  int(maxExclusive: number): number {
    return Math.floor(this.next() * maxExclusive);
  }
  /** Float in [min, max). */
  range(min: number, max: number): number {
    return min + this.next() * (max - min);
  }
  /** True with probability p. */
  chance(p: number): boolean {
    return this.next() < p;
  }
  /** Uniformly pick one element. */
  pick<T>(arr: readonly T[]): T {
    if (arr.length === 0) throw new Error("Rng.pick: empty array");
    return arr[this.int(arr.length)];
  }
  /** Pick `count` distinct elements (Fisher–Yates partial shuffle). */
  sample<T>(arr: readonly T[], count: number): T[] {
    const copy = arr.slice();
    const n = Math.min(count, copy.length);
    for (let i = 0; i < n; i++) {
      const j = i + this.int(copy.length - i);
      [copy[i], copy[j]] = [copy[j], copy[i]];
    }
    return copy.slice(0, n);
  }
  /** Return a shuffled copy. */
  shuffle<T>(arr: readonly T[]): T[] {
    const copy = arr.slice();
    for (let i = copy.length - 1; i > 0; i--) {
      const j = this.int(i + 1);
      [copy[i], copy[j]] = [copy[j], copy[i]];
    }
    return copy;
  }
  /** Weighted pick: weights align by index with items. */
  weighted<T>(items: readonly T[], weights: readonly number[]): T {
    const total = weights.reduce((a, b) => a + b, 0);
    let r = this.next() * total;
    for (let i = 0; i < items.length; i++) {
      r -= weights[i];
      if (r <= 0) return items[i];
    }
    return items[items.length - 1];
  }
}
